# Generated by Django 6.0.6 on 2026-09-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='has_limit',
        ),
        migrations.AddField(
            model_name='category',
            name='exclude_from_overview',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='is_misc',
            field=models.BooleanField(default=False),
        ),
    ]
