# Generated by Django 6.0.6 on 2026-10-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_category_has_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='type',
            field=models.CharField(choices=[('simple', 'Simple'), ('extended', 'Extended')], max_length=255),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='receipt_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='receiptitem',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='receiptitem_amount_positive'),
        ),
    ]
